apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include individual YAML files
resources:
  - demo-deployment.yaml
  - demo-policy.yaml
  - demo-service.yaml
  - frontend-ns.yaml
  - frontend-sa.yaml
  - deny-all-policy2.yaml

# Include policy folders (each has its own kustomization.yaml)
  #- gatekeeper
  - kyverno/baseline
