apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ImageDigestRequired
metadata:
  name: require-image-digest
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoImageLatest
metadata:
  name: disallow-image-latest
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]