apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisallowPlaintextSecrets
metadata:
  name: disallow-plaintext-secrets
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["frontend"]